### ISSUE TITLE
Will the new K quantizations be added anytime soon for StarCoder?

### ISSUE THREAD

**Issue by richardr1126** [ggerganov/ggml#278]
I just quantized to q4_0 with WizardCoder-15b, using the Starcoder examples folder in the repo.

I really want to be able to use **3-bit k quant** (Q3_K_M) with my model. Will this ever be possible? Or is it not possible with the starcoder models?

**Comment by saharNooby** [comment]
+1 for the question! `k_quants.h` and `k_quants.c` are missing in the main `ggml` repo. Is there a reason why this repo does not support k-quants yet?

(BTW, I've tried to copy-paste the k-quants files in `rwkv.cpp`, but the inference did not work because of assertion failure: `[ggml_is_transposed](ggml.c:6161: !ggml_is_transposed(a))`; I did not dig deeper)

**Comment by Green-Sky** [comment]
FYI, starcoder can now be used with llama.cpp https://github.com/ggerganov/llama.cpp/pull/3187
i did not check if it supports k-quants

**Comment by richardr1126** [comment]
> FYI, starcoder can now be used with llama.cpp [ggerganov/llama.cpp#3187](https://github.com/ggerganov/llama.cpp/pull/3187) i did not check if it supports k-quants

confirmed Starcoder k-quants do work on llama.cpp
