### ISSUE TITLE
Add a way to change the number of openblas threads in ggml

### ISSUE THREAD

**Issue by klosax** [ggerganov/ggml#452]
Openblas defaults to the maximum available threads (not physical cores) which is usually not optimal. User code should be able to control this directly to get optimal performance.

The number of threads used by openblas can be changed using:
```
void goto_set_num_threads(int num_threads);
void openblas_set_num_threads(int num_threads);
```
https://github.com/xianyi/OpenBLAS#setting-the-number-of-threads-at-runtime

**Comment by slaren** [comment]
This can also be configured with an environment variable, and ggml can use many different BLAS libraries, not only OpenBLAS. The goal in the long term is also to replace BLAS with our own matrix multiplication routines. Maybe we could add documentation about these environment variables rather than adding a temporary, library specific API?

**Comment by klosax** [comment]
> Maybe we could add documentation about these environment variables rather than adding a temporary, library specific API?

The main problem is that openblas defaults to max available threads. If control by user-code is not desirable, then maybe set it to physical cores minus the threads ggml needs? Environment variables are not very friendly to end-users..

**Comment by klosax** [comment]
Closing this since OpenBLAS does not seem to give any benefit at all anymore.
https://github.com/ggerganov/llama.cpp/pull/2372
