### ISSUE TITLE
What can be used instead ggml_get_backend()?

### ISSUE THREAD

**Issue by bsdero** [ggerganov/ggml#656]
``The last build broke https://github.com/leejet/stable-diffusion.cpp. 

I am trying to use the last ggml code. 

The code with problems is:
```

1294
1295             if (dst_tensor == NULL) {
1296                 continue;
1297             }
1298
1299             ggml_backend_t backend = ggml_get_backend(dst_tensor);
1300
1301             size_t nbytes_to_read = tensor_storage.nbytes_to_read();
1302
1303             if (backend == NULL || ggml_backend_is_cpu(backend)) {
1304                 // for the CPU and Metal backend, we can copy directly into the tensor
1305                 if (tensor_storage.type == dst_tensor->type) {
1306                     GGML_ASSERT(ggml_nbytes(dst_tensor) == tensor_storage.nbytes());

```

**Comment by slaren** [comment]
I think that @FSSRepo already solved these issues in https://github.com/leejet/stable-diffusion.cpp/pull/104. More generally, there isn't really any replacement to `ggml_get_backend` because buffers are no longer associated with any specific backend instance, and applications need to keep track of the backend being used in other way.

**Comment by bsdero** [comment]
Thanks a lot for the help.

This repository has the updated source code [https://github.com/FSSRepo/stable-diffusion.cpp](https://github.com/FSSRepo/stable-diffusion.cpp).

It seems like the updates has not been merged into the original repository [https://github.com/leejet/stable-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp)

Thanks for the help.
