### ISSUE TITLE
make: *** No rule to make target 'gpt-2'.  Stop.

### ISSUE THREAD

**Issue by sanliuyi901** [ggerganov/ggml#666]
make: *** No rule to make target 'gpt-2'.  Stop.
why

**Comment by astariul** [comment]
For context : 

When running the [GPT inference example](https://github.com/ggerganov/ggml/blob/master/README.md#gpt-inference-example), from the README, at the step `make -j4 gpt-2 gpt-j`, we get the following error : 

```
make: *** No rule to make target `gpt-2'.  Stop.
```

Any idea how to fix this ?

**Comment by slaren** [comment]
The gpt-2 example has been modified since that document was written, and currently that are multiple versions of it, meant to show how to use different features of `ggml`. The names of the targets are `gpt-2-ctx`, `gpt-2-alloc`, `gpt-2-backend` and `gpt-2-backend2`. You can use any of these instead.

This is still an issue, we need make one of these the default `gpt-2` target, or update the documentation.
